name: Automation CI

on: [push, pull_request]

jobs:
  main-pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Оновлено до v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5 # Оновлено до v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Code Quality (Flake8)
        run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Run Tests & Generate Report
        run: pytest --html=report.html --self-contained-html

      - name: Archive report
        uses: actions/upload-artifact@v4 # ОСНОВНЕ ВИПРАВЛЕННЯ ТУТ
        with:
          # v4 вимагає унікальні імена для кожного артефакту в матриці
          name: test-report-python-${{ matrix.python-version }} 
          path: report.html

  docker-build:
    needs: main-pipeline
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Оновлено до v4
      - name: Build Image
        run: docker build . -t my-app:latest
